// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bemevsvoentrlojsxsdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbWV2c3ZvZW50cmxvanN4c2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODc0MDQsImV4cCI6MjA2Nzk2MzQwNH0.hpJvBZ1yjCqI9tTnbbpnNeaA5B8V-cJ4xbjabFh8Gt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});